### ISSUE TITLE
[Feature Request] Add ability to change headers

### ISSUE THREAD

**Issue by mark-youssef** [Tcheu/craftcms-httprequest#4]
Can you add a headers option in the requestParams to be able to control the headers of the request?

**Comment by shenders13** [comment]
Hi all,
This is a deal breaker for me as I am sending a HTTP request to an API which manages Authentication through the Headers.

**Comment by kant312** [comment]
Hi all,
Somehow I only noticed this issue now. I think it can be done by adding an options array as fourth parameter of `get` and `post` methods. Something like:

```
craft.httpReq.get('http://domain.com/api/test', { "lang" : "fr" }, false, {
  headers: {
    "X-Security-Token": "..."
  }
})
```

What do you think? (and sorry about the delayed answer)
