### ISSUE TITLE
Craft 3 support

### ISSUE THREAD

**Issue by chrisrowe** [Tcheu/craftcms-httprequest#5]
Hey @kant312 I've used this plenty in C2 and loved it, do you have any plans to port this to Craft 3?

**Comment by kant312** [comment]
Hello @chrisrowe and thank you for your message, that's really nice to read! 
I considered porting the plugin at some point but found that this other plugin seemed to do the same job: https://github.com/lukeyouell/craft-fetch 
If you think that it's still interesting to port httprequest to Craft 3 I might still implement it though.

**Comment by chrisrowe** [comment]
Ah thanks @kant312 - that should do what I need for now. Many thanks!

**Comment by kant312** [comment]
@chrisrowe you're welcome.
